### ISSUE TITLE
play internet LiveTV streams

### ISSUE THREAD

**Issue by Yahoo-Mike** [infinityofspace/jellyfin_alexa_skill#14]
### Please describe which problem should be solved

Play jellyfin LiveTV video streams.

### Optional: Describe your idea for a solution

I have two commits to do this:   
- [add internet LiveTV streaming](https://github.com/Yahoo-Mike/jellyfin_alexa_skill/commit/439c18955b48087280874bc08ca7ddc451c88726#diff-de3e6b4172dfd1eb90d593eba69e7fff88c0ed8ea3d89b5a8853f8343a24e1b2)
- [bug fix: distinguish between livetv and video](https://github.com/Yahoo-Mike/jellyfin_alexa_skill/commit/d1c224da2fcefebe5ee39728f4a1b0a92f6a5ec4#diff-de3e6b4172dfd1eb90d593eba69e7fff88c0ed8ea3d89b5a8853f8343a24e1b2)

I'll wait until PR #12  and #13 are merged, before raising a PR to play LiveTV video streams.  The branch the two new commits are on has #12 and #13 pre-merged - if I push it now it will get messy.

BTW this is the last improvement I had in mind.  If there's something else you'd like me to look at, my email should be in the commit history.

**Comment by infinityofspace** [comment]
closed by PR #15
