### ISSUE TITLE
Minor bug with the Dockerfile and pip upgrade

### ISSUE THREAD

**Issue by paoloantinori** [infinityofspace/jellyfin_alexa_skill#18]
### Describe the bug

[comment]: <> (A clear and concise description of what the bug is.)

Minor bug with the `docker` build steps. `pip` fails to upgrade

### To Reproduce

[comment]: <> (Steps to reproduce the behavior.)

Just follow readme

### Expected behavior

[comment]: <> (A clear and concise description of what you expected to happen.)

Not to fail

### Versions

[comment]: <> (Please complete the following version information.)

 - Are you using the Docker image or the Python package?: [write docker or pip as answer]
 - jellyfin_alexa_skill: [you can use `pip show jellyfin_alexa_skill` to get the version]

### Additional context

[comment]: <> (Add any other context about the problem here. E.g. Logs and error messages.)

Logs:

```
[1/2] STEP 7/9: RUN pip3 install --upgrade pip && pip3 install -r requirements-docker-build.txt
Requirement already satisfied: pip in /opt/venv/lib/python3.10/site-packages (21.2.4)
Collecting pip
  Downloading pip-21.3.1-py3-none-any.whl (1.7 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 21.2.4
    Uninstalling pip-21.2.4:
ERROR: Could not install packages due to an OSError: [Errno 39] Directory not empty: 'webencodings'

[2/2] STEP 1/10: FROM python:3.10-alpine3.14
Error: error building at STEP "RUN pip3 install --upgrade pip && pip3 install -r requirements-docker-build.txt": error while running runtime: exit status 1
```

Fix: Just remove the `pip` upgrade step

**Comment by infinityofspace** [comment]
Thanks for your bug report.

Unfortunately, I cannot reproduce the reported error. Moreover the package `webencodings` is not a dependency of this project. So the error is somewhat strange.

If you have a modified or different version than the one from the current main branch, could you please provide the full Dockerfile. In addition, could you please also specify the OS / architecture you used.
