### ISSUE TITLE
Add support for video playback

### ISSUE THREAD

**Issue by infinityofspace** [infinityofspace/jellyfin_alexa_skill#2]
### Please describe which problem should be solved

[comment]: <> (A short and precise description of what problem the feature is supposed to address.)

The media player should also play video files from the Jellyfin server. At least the basic functions like start of a certain video and pause should be implemented. Currently only the audio playback works with the basic functions.

### Optional: Describe your idea for a solution

[comment]: <> (A short and precise description of how to solve the above problem..)

None

**Comment by Yahoo-Mike** [comment]
If no one has already started on this, can I have a go at this?

**Comment by infinityofspace** [comment]
Closed in PR #13
