### ISSUE TITLE
account linking fails

### ISSUE THREAD

**Issue by Yahoo-Mike** [infinityofspace/jellyfin_alexa_skill#5]
### Describe the bug

[comment]: <> (A clear and concise description of what the bug is.)

Alexa skill returns bad request (400) when attempting to link account.

### To Reproduce

[comment]: <> (Steps to reproduce the behavior.)

1. start jellyfin_alexa_skill
2. in Alexa app, attempt to link Jellyfin Player skill to account.

### Expected behavior

[comment]: <> (A clear and concise description of what you expected to happen.)

Expect to see jellyfin login screen in a browser.  Instead, "Bad Request (400)" error is displayed.

### Versions

[comment]: <> (Please complete the following version information.)

 - Are you using the Docker image or the Python package?: docker (locally built image)
 - jellyfin_alexa_skill: 0.2.1

### Additional context

[comment]: <> (Add any other context about the problem here. E.g. Logs and error messages.)

Issue is caused by VALID_ALEXA_REDIRECT_URLS_REGEX not recognising **_alexa.amazon.co.jp_** as valid.

alexa.amazon.co.jp is valid: see [Account Linking Schemas: Redirect URLs](https://developer.amazon.com/en-US/docs/alexa/smapi/account-linking-schemas.html#redirect-urls)

I think Amazon directs me to their Japanese site, because I'm in Australia.

### Suggested solution
The following fixed the problem for me.   In _config.py_:
```
VALID_ALEXA_REDIRECT_URLS_REGEX = re.compile(
    "https://((alexa)|(layla)|(pitangui))\.amazon(\.com|\.co\.jp)/spa/skill/account-linking-status\.html\?vendorId=.+"
)
```
...and yes there are other regex solutions, but I think this solution is the easiest to read.  

I can send this as a pull request, if you prefer.

**Comment by infinityofspace** [comment]
Thanks for your detailed bug report and suggestion for a customized new regex expression. You are right, the current implemented regex does not cover all valid base domains. I will revise the current regex expression again to cover all valid base domains. The fix will be included in the upcoming version `0.2.2`.
